// src/components/TagEditor/TagEditor.tsx
import * as React from "jsx-dom";
import { getGlobalData } from "@/utils/data";
import "./style.scss";

export const createTagEditor = async (root: HTMLElement, initial: string[]) => {
  const data = await getGlobalData();
  const allTags = [...new Set(data.map((p) => p.tags).flat())];
  const modelValue: string[] = [...initial];

  const changeListeners: any[] = [];
  const render = () => {
    const tagEditor = React.createRef();
    const tagsListWrapper = React.createRef();
    const createTag = (tag: string) => (
      <div key={tag} class="rounded px-3 py-1 cursor-pointer relative group tag">
        <button
          class="opacity-0 transition-delay-[0.25s] group-hover:opacity-100 absolute bg-red top-0 right-0 w-3 h-3 rounded-full flex items-center justify-center"
          onClick={() => toRemove(tag)}>
          <div class="i-ri:close-line text-white"></div>
        </button>
        #{tag}
      </div>
    );
    const tagList = () => modelValue.map(createTag);

    const tagsSelectionListWrapper = React.createRef();
    const tagSelectionList = () => {
      const otherTags = allTags.filter((t) => !modelValue.includes(t));
      return otherTags.map((tag) => (
        <button key={tag} class="text-button text-gray hover:text-black" onClick={() => toAddTag(tag)}>
          #{tag}
        </button>
      ));
    };
    const tagInput = React.createRef();

    const toRemove = (t: string) => {
      modelValue.splice(
        modelValue.findIndex((v) => v === t),
        1
      );
      (tagsListWrapper.current as HTMLElement)?.replaceChildren(...tagList());
      (tagsSelectionListWrapper.current as HTMLElement)?.replaceChildren(...tagSelectionList());
      changeListeners.forEach((f) => f());
    };
    const toAddTag = (v?: string) => {
      const newV = v ?? tagInput.current.value;
      if (!newV) return;
      if (modelValue.includes(newV)) return;
      if (tagInput.current.value) {
        tagInput.current.value = "";
        tagEditor.current.blur();
      }
      modelValue.push(newV);
      (tagsListWrapper.current as HTMLElement)?.replaceChildren(...tagList());
      (tagsSelectionListWrapper.current as HTMLElement)?.replaceChildren(...tagSelectionList());
      changeListeners.forEach((f) => f());
    };

    return (
      <div ref={tagEditor} class="tag-editor flex text-sm px-4 gap-2 w-full max-w-[720px]">
        <div ref={tagsListWrapper} class="flex gap-2">
          {tagList()}
        </div>
        <div class="relative add-tag">
          <button class="rounded text-gray hover:bg-gray-200 px-2 py-1 cursor-pointer">#Add a Tag</button>
          <div class="absolute z-[50] tag-selector">
            <div class="flex flex-col bg-white shadow-md rounded p-2 gap-2 text-sm">
              <div class="flex items-center justify-center gap-2">
                <input
                  ref={tagInput}
                  type="text"
                  class="border px-2 py-1 rounded border-blue w-[180px] text-xs"
                  placeholder="Create new Tag"
                />
                <button class="text-button text-blue" onClick={() => toAddTag()}>
                  Add
                </button>
              </div>
              <div ref={tagsSelectionListWrapper} class="flex flex-col">
                {tagSelectionList()}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  root.appendChild(render());
  return {
    getValue: () => modelValue,
    onChange: (fn: any) => {
      changeListeners.push(fn);
      return () =>
        changeListeners.splice(
          changeListeners.findIndex((f) => f === fn),
          1
        );
    },
  };
};

// render/components/TagEditor.vue
<template>
  <div class="tag-editor flex text-sm px-4 gap-2">
    <div
      v-for="tag in modelValue"
      :key="tag"
      class="rounded px-3 py-1 cursor-pointer relative group tag"
    >
      <button
        class="opacity-0 transition-delay-[0.25s] group-hover:opacity-100 absolute bg-red top-0 right-0 w-3 h-3 rounded-full flex items-center justify-center"
        @click="() => toRemove(tag)"
      >
        <div class="i-ri:close-line text-white"></div>
      </button>
      #{{ tag }}
    </div>
    <div class="relative add-tag" tabindex="-1">
      <button
        class="rounded text-gray hover:bg-gray-200 px-2 py-1 cursor-pointer"
      >
        #Add a Tag
      </button>
      <div class="absolute z-[50] tag-selector">
        <div class="flex flex-col bg-white shadow-md rounded p-2 gap-2 text-sm">
          <div class="flex items-center justify-center gap-2">
            <input
              v-model="newTag"
              type="text"
              class="border px-2 py-1 rounded border-blue w-[180px] text-xs"
              placeholder="Create new Tag"
            />
            <button
              class="text-button text-blue"
              @click="(e) => toAddTag(e, newTag)"
            >
              Add
            </button>
          </div>
          <template v-if="data">
            <button
              v-for="tag in tags"
              :key="tag"
              class="text-button text-gray hover:text-black"
              @click="(e) => toAddTag(e, tag)"
            >
              #{{ tag }}
            </button>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { computed, ref } from "vue";
import { usePageData } from "../hooks/page";

const props = defineProps<{
  modelValue: string[];
}>();
const emit = defineEmits<{
  (name: "update:modelValue", value: string[]): void;
}>();

const newTag = ref("");
const toAddTag = (e: MouseEvent, tag: string) => {
  if (!tag) return;
  emit("update:modelValue", [...new Set([...props.modelValue, tag])]);
  newTag.value = "";
  (e.target as HTMLElement)?.blur();
};

const data = usePageData();

const allTags = computed(() => [
  ...new Set(data.value.pageData.map((v) => v.tags).flat()),
]);
const tags = computed(
  () => allTags.value.filter((t) => !props.modelValue.includes(t)) ?? []
);

const toRemove = (tag: string) => {
  emit(
    "update:modelValue",
    props.modelValue.filter((v) => v !== tag)
  );
};
</script>
<style lang="scss" scoped>
.tag {
  transition: all ease 0.25s;
  transition-delay: 0.25s;
  --opacity: 0;
  --stop: 0%;
  background: linear-gradient(
    90deg,
    rgba(229, 231, 235, var(--opacity)) 50%,
    rgb(248 113 113 / 1) 50%,
    rgb(248 113 113 / 1) 100%
  );
  background-position: 0%;
  background-size: 200%;
  &:hover {
    --opacity: 1;
    background-position: 100%;
    color: white;
  }
}

.add-tag {
  .tag-selector {
    display: none;
  }
  &:focus-within {
    .tag-selector {
      display: block;
    }
  }
}
</style>
